%% Main.m
% =========================================================================
% NEURONAL DATA ANALYZER - MAIN LAUNCHER
% =========================================================================
% Entry point for the NeuroAnalyzer application (NMD Lab). On first run (or
% when no project dirs are set), prompts for Import/Export directories.
% Two main sections: (1) Filtering & Signal Processing (LDF and Ephys tools),
% (2) Signal Characterization (feature extraction from processed data).
% Project bar shows current Import/Export paths and "Set Directories" button.
% =========================================================================

classdef Main < handle
    properties
        UIFig
        HeaderPanel
        ProjectPanel
        ImportLabel
        ExportLabel
        ContentPanel
        % Section 1: Filtering & Signal Processing
        ProcessingPanel    % Card containing LDF and Ephys panels
        LDFPanel
        EphysPanel
        ExtractLDFBtn
        ProcessLDFBtn
        AverageLDFBtn
        ExtractEphysBtn
        LFPAnalysisBtn
        ProcessMUABtn
        % Section 2: Signal Characterization
        CharPanel
        CharBtn            % Open Signal Characterization
        HelpBtn
        AuthorLabel
    end

    methods
        function app = Main()
            app.buildUI();
            % Prompt for project directories if not set (optional: only when no dirs)
            if ~ProjectManager.hasProject()
                ProjectManager.promptForProjectDirs();
                app.updateProjectLabels();
            end
        end

        function buildUI(app)
            T = UITheme;
            app.UIFig = uifigure('Name', 'Neuronal Data Analyzer', ...
                'Position', [420 120 900 620], 'Resize', 'on', 'Color', T.bgGray);

            % === HEADER ===
            app.HeaderPanel = uipanel(app.UIFig, ...
                'Position', [0 560 900 60], ...
                'BackgroundColor', T.headerBg, 'BorderType', 'none');
            uilabel(app.HeaderPanel, 'Text', 'Neuronal Data Analyzer', ...
                'Position', [24 22 420 26], ...
                'FontSize', T.fontTitle, 'FontWeight', 'bold', 'FontColor', T.headerTitleColor);
            uilabel(app.HeaderPanel, 'Text', 'NMD Lab', ...
                'Position', [24 6 120 18], ...
                'FontSize', T.fontSubtitle, 'FontColor', T.headerSubtitleColor);
            app.HelpBtn = uibutton(app.HeaderPanel, 'push', ...
                'Text', 'Help', ...
                'Position', [800 14 80 32], ...
                'BackgroundColor', [1 1 1], 'FontColor', T.headerBg, ...
                'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~)HelpApp());

            % === PROJECT BAR: Import / Export dirs, Set Directories ===
            app.ProjectPanel = uipanel(app.UIFig, ...
                'Position', [0 508 900 52], ...
                'BackgroundColor', T.projectBarBg, ...
                'BorderType', 'line', 'HighlightColor', T.projectBarBorder);
            uilabel(app.ProjectPanel, 'Text', 'Import:', ...
                'Position', [14 28 50 18], 'FontWeight', 'bold', 'FontSize', T.fontSmall);
            app.ImportLabel = uilabel(app.ProjectPanel, 'Text', '(not set)', ...
                'Position', [64 28 320 18], 'FontSize', T.fontSmall, ...
                'FontColor', T.bodyColor, 'Interpreter', 'none');
            uilabel(app.ProjectPanel, 'Text', 'Export:', ...
                'Position', [394 28 50 18], 'FontWeight', 'bold', 'FontSize', T.fontSmall);
            app.ExportLabel = uilabel(app.ProjectPanel, 'Text', '(not set)', ...
                'Position', [444 28 320 18], 'FontSize', T.fontSmall, ...
                'FontColor', T.bodyColor, 'Interpreter', 'none');
            uibutton(app.ProjectPanel, 'push', ...
                'Text', 'Set Directories', ...
                'Position', [780 12 100 28], ...
                'ButtonPushedFcn', @(~,~)app.onSetDirectories());

            % === CONTENT: two sections ===
            app.ContentPanel = uipanel(app.UIFig, ...
                'Position', [16 52 868 456], ...
                'BackgroundColor', T.bgGray, 'BorderType', 'none');

            % --- SECTION 1: Filtering & Signal Processing ---
            uilabel(app.ContentPanel, 'Text', '1. Filtering & Signal Processing', ...
                'Position', [10 428 380 22], ...
                'FontSize', T.fontSection, 'FontWeight', 'bold', 'FontColor', T.sectionTitleColor);
            app.ProcessingPanel = uipanel(app.ContentPanel, ...
                'Title', '', 'Position', [10 120 868 308], ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'BorderType', 'line');

            % LDF card (left half)
            app.LDFPanel = uipanel(app.ProcessingPanel, ...
                'Title', 'LDF (Laser Doppler Flowmetry)', ...
                'Position', [12 12 418 282], ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            lGrid = uigridlayout(app.LDFPanel, [4, 1], ...
                'RowHeight', {'1x', '1x', '1x', 24}, ...
                'Padding', [14 12 14 12], 'RowSpacing', 10);
            app.ExtractLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Extract LDF Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load and extract LDF; crop and save', ...
                'ButtonPushedFcn', @(~,~)ExtractLDFApp());
            app.ProcessLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Process LDF Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Filter and segment LDF by stimulus', ...
                'ButtonPushedFcn', @(~,~)ProcessingLDFApp());
            app.AverageLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Average LDF Viewer', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Grand average across trials', ...
                'ButtonPushedFcn', @(~,~)LDFGrandAverageApp());
            uilabel(lGrid, 'Text', 'Load → Crop → Process → Average', ...
                'FontSize', T.fontTiny, 'FontColor', T.mutedColor);

            % Ephys card (right half)
            app.EphysPanel = uipanel(app.ProcessingPanel, ...
                'Title', 'Electrophysiology', ...
                'Position', [438 12 418 282], ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            eGrid = uigridlayout(app.EphysPanel, [4, 1], ...
                'RowHeight', {'1x', '1x', '1x', 24}, ...
                'Padding', [14 12 14 12], 'RowSpacing', 10);
            app.ExtractEphysBtn = uibutton(eGrid, 'push', ...
                'Text', 'Extract Ephys Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load TDT; extract LFP and MUA', ...
                'ButtonPushedFcn', @(~,~)ExtractEphysApp());
            app.LFPAnalysisBtn = uibutton(eGrid, 'push', ...
                'Text', 'Process LFP Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'ERP and CSD analysis', ...
                'ButtonPushedFcn', @(~,~)LFPAnalysisApp());
            app.ProcessMUABtn = uibutton(eGrid, 'push', ...
                'Text', 'Process MUA Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Spike sorting and rate', ...
                'ButtonPushedFcn', @(~,~)MUAAnalysisApp());
            uilabel(eGrid, 'Text', 'TDT → LFP / MUA → ERP, CSD, spikes', ...
                'FontSize', T.fontTiny, 'FontColor', T.mutedColor);

            % --- SECTION 2: Signal Characterization ---
            uilabel(app.ContentPanel, 'Text', '2. Signal Characterization', ...
                'Position', [10 98 320 22], ...
                'FontSize', T.fontSection, 'FontWeight', 'bold', 'FontColor', T.sectionTitleColor);
            app.CharPanel = uipanel(app.ContentPanel, ...
                'Title', 'Extract response features from processed or imported data', ...
                'Position', [10 12 868 86], ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            cGrid = uigridlayout(app.CharPanel, [1, 2], ...
                'ColumnWidth', {'1x', 220}, 'Padding', [16 14 16 14]);
            uilabel(cGrid, 'Text', ...
                'Peak latency, onset delay, FWHM, AUC (positive/negative), rise/decay time, stimulation–response integration.', ...
                'FontSize', T.fontSmall, 'FontColor', T.bodyColor, 'WordWrap', 'on');
            app.CharBtn = uibutton(cGrid, 'push', ...
                'Text', 'Open Signal Characterization', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load processed data and extract response features', ...
                'ButtonPushedFcn', @(~,~)SignalCharacterizationApp());

            % --- FOOTER ---
            app.AuthorLabel = uihyperlink(app.UIFig, ...
                'Text', '© Copyrights by Alejandro Suarez, Ph.D.', ...
                'URL', 'https://github.com/alesuarez92', ...
                'Position', [550 6 330 18], 'FontSize', T.fontSmall, ...
                'FontColor', T.mutedColor, 'HorizontalAlignment', 'right');

            app.updateProjectLabels();
        end

        function onSetDirectories(app)
            ProjectManager.promptForProjectDirs();
            app.updateProjectLabels();
        end

        function updateProjectLabels(app)
            imp = ProjectManager.getImportDir();
            exp = ProjectManager.getExportDir();
            if isempty(imp), imp = '(not set)'; else imp = pathShorten(imp, 42); end
            if isempty(exp), exp = '(not set)'; else exp = pathShorten(exp, 42); end
            app.ImportLabel.Text = imp;
            app.ExportLabel.Text = exp;
        end
    end
end

function s = pathShorten(p, maxLen)
    if length(p) <= maxLen
        s = p;
        return;
    end
    s = ['...' p(end-maxLen+3:end)];
end
